<?php

namespace Fridde\Entities;

use Carbon\Carbon;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping AS ORM;
use Fridde\Annotations\AutoGenerated;

/**
 * @ORM\Entity(repositoryClass="Fridde\Entities\TopicRepository")
 * @ORM\Table(name="topics")
 * @ORM\HasLifecycleCallbacks
 */
class Topic
{
    /** @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue
     */
    protected $id;

    /** @ORM\Column(type="string", nullable=true) */
    protected $Segment;

    /** @ORM\Column(type="smallint")
     *  @AutoGenerated  */
    protected $VisitOrder = -1;

    /** @ORM\Column(type="string") */
    protected $ShortName;

    /** @ORM\Column(type="string", nullable=true) */
    protected $LongName;

    /** @ORM\ManyToOne(targetEntity="Location", inversedBy="Topics")     * */
    protected $Location;

    /** @ORM\Column(type="string", nullable=true) */
    protected $Food;

    /** @ORM\Column(type="smallint", nullable=true) */
    protected $FoodOrder;

    /** @ORM\Column(type="string", nullable=true) */
    protected $Url;

    /** @ORM\Column(type="smallint", nullable=true) */
    protected $IsLektion;

    /** @ORM\Column(type="smallint", nullable=true) */
    protected $OrderIsRelevant;

    /** @ORM\Column(type="string", nullable=true) */
    protected $LastChange;

    /** @ORM\OneToMany(targetEntity="Visit", mappedBy="Topic")   * */
    protected $Visits;

    // byo means "bring your own" and means in this context that the group
    // provides for their own food
    public const FOOD_NONE = 0;
    public const FOOD_ORDER = 1;
    public const FOOD_NOTIFY = 2;

    public const FOOD_ORDER_TYPES = [
        0 => 'no_order_needed',
        1 => 'order_from_kitchen',
        2 => 'notify_kitchen',
    ];

    public function __construct()
    {
        $this->Visits = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getSegment()
    {
        return $this->Segment;
    }

    public function getSegmentLabel()
    {
        $labels = Group::getSegmentLabels();

        return $labels[$this->getSegment()];
    }

    public static function getSegmentLabels()
    {
        return Group::getSegmentLabels();
    }

    public function setSegment($Segment)
    {
        $this->Segment = $Segment;
    }

    public function getVisitOrder(): ?int
    {
        return $this->VisitOrder;
    }

    public function setVisitOrder(int $VisitOrder)
    {
        $this->VisitOrder = $VisitOrder;
    }

    public function getShortName()
    {
        return $this->ShortName;
    }

    public function setShortName($ShortName)
    {
        $this->ShortName = $ShortName;
    }

    public function getLongName()
    {
        return $this->LongName;
    }

    public function setLongName($LongName)
    {
        $this->LongName = $LongName;
    }

    public function getLongestName()
    {
        $long = $this->getLongName();
        if (empty($long)) {
            return $this->getShortName();
        }

        return $long;
    }

    public function getLocation(): ?Location
    {
        return $this->Location;
    }

    public function getLocationId()
    {
        $location = $this->getLocation();
        if(empty($location)){
            return null;
        }
        return $location->getId();
    }

    public function setLocation($Location)
    {
        $this->Location = $Location;
    }

    public function getFood()
    {
        return $this->Food;
    }

    public function setFood($Food)
    {
        $this->Food = $Food;
    }

    public function getFoodOrder()
    {
        return $this->FoodOrder;
    }

    public function setFoodOrder(int $FoodOrder)
    {
        $this->FoodOrder = $FoodOrder;
    }


    public function getUrl()
    {
        return $this->Url;
    }

    public function setUrl($Url)
    {
        $this->Url = $Url;
    }

    public function getIsLektion()
    {
        return (boolean) $this->IsLektion;
    }

    public function isLektion()
    {
        return $this->getIsLektion();
    }

    public static function getIsLektionOptions()
    {
        return [0 => 'No', 1 => 'Yes'];
    }

    public function setIsLektion($IsLektion)
    {
        $this->IsLektion = (int)$IsLektion;
    }

    /**
     * @return bool
     */
    public function getOrderIsRelevant(): bool
    {
        return (bool) $this->OrderIsRelevant;
    }

    /**
     * @param boolean $OrderIsRelevant
     */
    public function setOrderIsRelevant(bool $OrderIsRelevant): void
    {
        $this->OrderIsRelevant = $OrderIsRelevant;
    }

    public static function getOrderIsRelevantOptions()
    {
        return [0 => 'No', 1 => 'Yes'];
    }



    public function getLastChange()
    {
        return $this->LastChange;
    }

    public function setLastChange($LastChange)
    {
        $this->LastChange = $LastChange;
    }

    public function getVisits()
    {
        return $this->Visits;
    }

    /** @ORM\PrePersist */
    public function prePersist()
    {
        $this->setLastChange(Carbon::now()->toIso8601String());
    }

    /** @ORM\PreUpdate */
    public function preUpdate()
    {
        $this->setLastChange(Carbon::now()->toIso8601String());
    }

    /** @ORM\PreRemove */
    public function preRemove()
    {
    }

}
