#!/bin/bash

SKIP=0
while getopts "s:" opts; do
   case ${opts} in
      s) SKIP=${OPTARG} ;;
   esac
done

#Variable names
PROJECT_NAME=naturskolan_database
PROJECT_PATH=~/$PROJECT_NAME
TESTING_PATH=~/testing
TESTDB_PATH=$TESTING_PATH/$PROJECT_NAME/tests/_data/test_db.sql
STAGING_PATH=/cygdrive/d/staging
GITHUB_PROJECT=https://github.com/fridde/naturskolan_database.git

set -x
trap read debug

if [ $SKIP -lt 1 ]; then
    echo 'Backup DB and export to test-DB'
    cd $PROJECT_PATH/misc
    php -e export_database.php default > $TESTDB_PATH
    php -e export_database.php just_data > /dev/null
    php -e export_database.php structure > /dev/null
    php -e "$PROJECT_PATH/tests/ods_to_sql.php" >> $TESTDB_PATH
    cd SQL_data
    delete_old_files

fi

if [ $SKIP -lt 2 ]; then

   cd $TESTING_PATH/$PROJECT_NAME
   git status
   echo 'Proceed if your .gitignore file is configured correctly!'
   git add -A
   git commit -m 'Continue more testing'
   git push
   echo 'Pulling repo changes into dev area'
   cd $PROJECT_PATH
   git pull

fi

if [ $SKIP -lt 3 ]; then
    echo 'Synchronizing the work in vendor with the toolbox'
    cd ~
    filecomparer

    cd ~/toolbox

    gitstatus
    echo 'Enter the names of the packages that you will commit.'
    read P_NAMES
    set_package_date -a fridde -p "$P_NAMES"
    echo 'If some repos have to be pushed, use Win+Alt+X to open a new split window.'
fi

if [ $SKIP -lt 4 ]; then
    trap - debug
    set +x

    echo "Have you..."
    echo "1. run filecomparer?"
    echo "2. Committed and pushed all changes inside the toolbox directories?"

    while true; do
        read -e -p "yes or no?  " yn
        case $yn in
            [Yy]* ) echo ""; break;;
            [Nn]* ) exit;;
            * ) echo "Please answer yes or no.";;
        esac
    done

    set -x
    trap read debug

    echo 'Update own composer packages and push changes'
    cd ~/toolbox
    while true; do
        compare_package_date
        read -e -p "Updated?  " answer
        case $answer in
            [Yy]* ) echo ""; break;;
            * ) echo "Trying again";;
        esac
    done

    cd $PROJECT_PATH
    composer update fridde/*
    composer install
    git status

    trap - debug
    set +x
    read -p "Is the .gitignore file correctly configured?  " yn
        case $yn in
            [Yy]* ) ;;
            [Nn]* ) exit;;
            * ) echo "Please answer yes or no.";;
        esac
    set -x
    trap read debug

    git add -A
    git commit -m "More work"
    git push
fi

if [ $SKIP -lt 5 ]; then
    cd $TESTING_PATH
    delete_old_files
    tar cf backup_@`date '+%Y%m%d_%H%M%S'`.tar $PROJECT_NAME

    cd $PROJECT_NAME
    git pull
    composer install --no-suggest
    cp $PROJECT_PATH/config/settings_{default,test}.yml ./config/
    mv ./config/settings_{test,local}.yml
fi

if [ $SKIP -lt 6 ]; then
    echo 'Setting up local testing environment'
    trap - debug ; set +x
    cd ~/bin_win
    cmd /C start java -jar selenium-server.jar &
    cmd /C start MailHog.exe &
    cd $TESTING_PATH/$PROJECT_NAME
    set -x ; trap read debug
    ./vendor/bin/codecept run -f --steps
fi

if [ $SKIP -lt 7 ]; then
    echo 'Creating the local staging copy...'
    cd $STAGING_PATH
    delete_old_files
    tar cf backup_`date '+%Y%m%d_%Hx%Mx%S'`.tar $PROJECT_NAME
    chmod -R 0777 $PROJECT_NAME && rm -rf $PROJECT_NAME

    git clone --depth 1 $GITHUB_PROJECT
    cd $PROJECT_NAME
    composer install --no-dev --no-suggest
fi

if [ $SKIP -lt 8 ]; then
    echo 'Uploading the changed files to the remote server...'
    cp $PROJECT_PATH/deployment/deployment.ini $STAGING_PATH/deployment/deployment.ini
    cp $PROJECT_PATH/config/settings_prod.yml $STAGING_PATH/config/settings_local.yml

    ./vendor/bin/deployment deployment/deployment.ini
fi



