NAV_SETTINGS:
  base:
    - &home
      label: 'Start'
      url: '#'
    - &support
      label: 'Hjälp'
      url: 'support'
    - &school
      label: 'Hem'
      url: '->getSchoolPageUrl(school_id)'
    - &contact
      label: 'Kontakt'
      url: 'contact'

  admin:
    -
      label: 'Skolor'
      children: '->getAllSchoolUrls'
    -
      label: 'Verktyg'
      children:
         -
           label: 'Översikt'
           url: 'admin'
         -
           label: 'Redigera arbetsfördelningen'
           url: 'admin/batch/set_colleagues'
         -
           label: 'Kontrollera bus & mat'
           url: 'admin/batch/set_bookings'
         -
           label: 'Lägg till besöksdatum till tema'
           url: 'admin/batch/add_dates'
         -
           label: 'Fördela besök på grupper'
           url: 'admin/batch/distribute_visits'
         -
           label: 'Uppdatera önskat antal grupper per skola'
           url: 'admin/batch/set_group_count'
         -
           label: 'Ordna om besöksordningen för teman'
           url: 'admin/batch/set_visit_order_for_topics'
         -
           label: 'Redigera bussinställningar'
           url: 'admin/batch/set_bus_settings'
         -
           label: 'Redigera kalendern'
           url: 'table/Event'
         -
           label: 'Boka buss'
           url: 'view/bus_order'
         -
           label: 'Beställ mat'
           url: 'view/food_order'
         -
           label: 'Anteckningar översikt'
           url: 'admin/show_note_calendar'
         -
           label: 'Visa logg'
           url: 'admin/show_log'
    -
      label: 'Tabeller'
      children: '->getAllTableUrls'
  user:
    -
      <<: *school
    -
      <<: *support
    -
      <<: *contact

  guest:
    -
      <<: *home
    -
      <<: *support
    -
      <<: *contact
