# keys will be parsed as the name of the route
# the default action is handleRequest()
routes:
   index: ['GET','','Page#viewIndex']
   admin : ['GET','/admin/[:action]?','Admin']
   api : ['GET|POST','/api/[:action]/[**:parameters]?', 'API']
   batch : ['GET|POST','/admin/batch/[:action]/[**:parameters]?','Batch']
   calendar: ['GET','/calendar','File#getCalendar']
   contact: ['GET', '/contact', 'Page#showContact']
   cron : ['GET','/cron/[:AuthKey]?','Cron']
   file : ['GET','/file/[:file1]/[:file2]?/[:file3]?','File#include']
   login : ['GET', '/login/[:code]/[**:destination]?', 'Login#login_with_code']
   logout: ['GET', '/logout', 'Login#logout']
   note: ['GET|POST', '/notes/[:visit_id]', 'Admin#editNote']
   pwrecover : ['GET','/passwordrecover/[:code]?','API#passwordRecover']
   sandbox: ['GET|POST','/sandbox/[:action]?/[**:parameters]?', 'Sandbox']
   school : ['GET','/skola/[a:school]','School']
   sms : ['GET|POST','/sms/[:action]?','API']
   support: ['GET', '/support/[:section]?', 'Page#showSupport']
   table : ['GET','/table/[a:entity]','Table#view']
   task : ['GET','/task/[:type]/[:AuthKey]?','Cron#executeTaskNow']
   update : ['POST','/update','Update']
   view : ['GET','/view/[:page]','View']



#200 = ['GET', '[**:url]', 'Error#notFound']

# ['','','']
