# keys will be parsed as the name of the route
# the default action is handleRequest()
routes:
   admin : ['GET','/admin/[:action]?','Admin']
   api : ['GET|POST','/api/[:action]/[**:parameters]?', 'API']
   batch : ['GET','/admin/batch/[:action]/[**:parameters]?','Batch']
   checkpw : ['GET','/login/[:password]?','Login#checkPassword']
   cron : ['GET','/cron/[:AuthKey]?','Cron']
   file : ['GET','/file/[:file1]/[:file2]?/[:file3]?','File#include']
   login : ['GET', '/login/[:code]', 'Login#login']
   logout: ['GET', '/logout', 'Login#logout']
   pwrecover : ['GET','/passwordrecover/[:code]?','API#passwordRecover']
   sandbox: ['GET|POST','/sandbox/[:action]?/[**:parameters]?', 'Sandbox']
   school : ['GET','/skola/[a:school]/[a:page]?','School']  # changing this affects Navigation::getStaffPageUrl()
   sms : ['GET|POST','/sms/[:purpose]?/[:encoding]?','SMS']
   table : ['GET','/table/[a:entity]','Table#view']
   task : ['GET','/task/[:type]','Cron#executeTask']
   update : ['POST','/update','Update']
   view : ['GET','/view/[:page]','View']
   default: ['GET','/[**:url]?','Page']


#200 = ['GET', '[**:url]', 'Error#notFound']

# ['','','']
