[routes]
0 = ['GET|POST','/skola/[a:school]/[a:page]?','School#handleRequest']
1 = ['POST','/update','Update#handleRequest']
10 = ['GET','/cron','Cron#execute']
11 = ['GET','/login','Login#getModal']
12 = ['GET','/login/[a:password]','Login#checkPassword']
20 = ['GET','/','Login#checkCookie']
30 = ['GET','/sandbox','File#renderSandbox']
31 = ['GET','/file/[:file1]/[:file2]?/[:file3]?','File#include']
40 = ['GET','/table/[a:entity]','Table#view']
#50 = ['','','']
#60 = ['','','']
#70 = ['','','']
#80 = ['','','']
#90 = ['','','']
#100 = ['','','']
#110 = ['','','']
#120 = ['','','']
#130 = ['','','']
#140 = ['','','']
#150 = ['','','']
#160 = ['','','']
#170 = ['','','']
#180 = ['','','']
#190 = ['','','']
#200 = ['GET', '[**:url]', 'Error#notFound']

# ['','','']
