[routes]
0 = ['GET|POST','/skola/[a:school]/[a:page]?/[:code]?','School#handleRequest', "school"]
1 = ['POST','/update','Update#handleRequest']
10 = ['GET','/cron','Cron#execute']
12 = ['GET','/login/[:password]?','Login#checkPassword']
20 = ['GET','/','Login#checkCookie']
30 = ['GET','/sandbox','File#renderSandbox']
31 = ['GET','/file/[:file1]/[:file2]?/[:file3]?','File#include']
40 = ['GET','/table/[a:entity]','Table#view']
50 = ['GET|POST','/cron/[i:counter]?','Cron#execute']
60 = ['GET|POST','/mail/[:type]?','Mail#send', "mail"]
61 = ['GET|POST','/sms/[:type]?','SMS#send', "sms"]
65 = ['GET','/passwordreset','API#passwordReset']
70 = ['GET','/passwordrecover/[:code]?','API#passwordRecover', 'pwrecover']
80 = ['GET','/confirm/[:code]','API#confirmVisit', 'confirmvisit']
#90 = ['','','']
#100 = ['','','']
#110 = ['','','']
#120 = ['','','']
#130 = ['','','']
#140 = ['','','']
#150 = ['','','']
#160 = ['','','']
#170 = ['','','']
#180 = ['','','']
#190 = ['','','']
#200 = ['GET', '[**:url]', 'Error#notFound']

# ['','','']
