# keys will be parsed as the name of the route
# the default action is handleRequest()
routes:
   index: ['GET','','Page','viewIndex']
   admin : ['GET','/admin/{action}','Admin', ~, 'action']
   api : ['GET|POST','/api/{action}/{parameters}', 'API', ~, {parameters: '.+'}]
   batch : ['GET|POST','/admin/batch/{action}/{parameters}','Batch', ~, 'parameters']
   calendar: ['GET','/calendar','File','getCalendar']
   contact: ['GET', '/contact', 'Page','showContact']
   cron : ['GET','/cron','Cron']
   login : ['GET', '/login/{code}/{destination}', 'Login','login_with_code', 'destination']
   logout: ['GET', '/logout', 'Login','logout']
   note: ['GET|POST', '/notes/{visit_id}', 'Admin','editNote']
   pwrecover : ['GET','/passwordrecover/{code}','API','passwordRecover']
   remove: ['GET','/remove/{school}','School','createRemoveUserPage']
   sandbox: ['GET|POST','/sandbox/{action}/{parameters}', 'Sandbox', {0: 'action', parameters: '.+'}]
   school : ['GET','/skola/{school}','School','createSchoolPage']
   sms : ['GET|POST','/sms/{action}','API', ~, 'action']
   support: ['GET', '/support/{section}', 'Page','showSupport', 'section']
   table : ['GET','/table/{entity}','Table','view']
   task : ['GET','/task/{type}/{AuthKey}','Cron','executeTaskNow', 'AuthKey']
   update : ['POST','/update','Update']
   view : ['GET','/view/{page}','View']



#200 = ['GET', '[**:url]', 'Error#notFound']

# ['','','']
