environment: dev
#environment: prod

Connection_Details:
  db_host :  '123.45.67.890'
  db_name : 'example_db'
  db_username : 'root'
  db_password : 'abcdef12345'

ORM:
  default_namespace : '\Fridde\Entities'

debug:
  mail : 'info@example.org'
  mobil : '+46123456789'
  base_path : 'http://www.example.org'

smtp_settings:
  from : 'info@example.org'
  host : 'smtp.example.org'
  password : 'abcd1234'
  username : 'admin@example.org'

cronjobs:
  slot_duration : [15, m]
  # delay : [3, h] # time after midnight when daily tasks are executed.  = 3am
  delay : [0, h] # use 3h in production
  max_calendar_age : [24, h]

  intervals:
    rebuild_calendar : [15, m]
    send_visit_confirmation_message : [24, h]
    send_admin_summary_mail : [24, h]
    send_changed_groupleader_mail : [24, h]
    send_new_user_mail : [6, h]
    send_update_profile_reminder : [4, d]
    clean_sql_database : [2, d]
    backup_database: [1, d]

admin:
  table_menu_items: [Event, Group, Location, School, Topic, User, Visit]
  summary:
    # who should the summary go to?
    admin_adress : '???'
    # time before a non-confirmed visit shows up in the mail
    no_confirmation_warning : [5, d]
    # time until the last visit before a warning is issued
    soon_last_visit : [60, d]
    # time to next visit within which a warning is issued if number of
    # students or food restrictions are changed
    important_info_changed : [21, d]
    # minimum and maximum number of students in a group. If not in this range, a warning is issued
    allowed_group_size : [5, 33]

user_message:
  # time after user creation until reminders are sent
  immunity_time : [9, d]
  # interval between reminders
  annoyance_interval : [4, d]
  visit_confirmation_time : [14, d]

sms_settings:
  google_api_key : 'a1b2c3d4e5f6g7h8i9'
  default_gateway : 'smsgateway'

  46elks:
    from : '+46123456789'
    password : 'A1B2C3D4'
    url : 'https://api.46elks.com/a1/'
    username : 'abcd1234efgh6789'

  smsgateway:
    callback_secret : 'abcd1234'
    device : '12345' # The id of the device
    email : 'info@example.org'
    password : 'abcde12345'

  telerivet:
    api_key : 'abcde1234fghei56789'
    project_id : 'A1B2C3D4E5F6'

slacker:
  webhook_url : 'https://hooks.slack.com/services/A1B2C3D4/L9K8J7H6/abcdefg123456'
  username : 'My Example Database'
  channel : '#administration'

segments: { 2: 'åk 2/3', 5: 'åk 5', fbk: 'FBK'}  # the first denotes the default segment in views

values:
  show_confirm_link : [30, d] # time before the confirmation link is shown in the group settings
  school_pw_validity : 3 # nr of calendar years that a school password is valid
  pw_salt : 'abcdefgh12345678'
  api_key : 'abcd12345'

  min_max_students:
    min : 5
    max : 35 # the minimum and maximum of students allowed in each group

calendar:
  default_start_time : [8,15] # [hours, minutes]
  default_end_time : [13,30] # [hours, minutes]
  lektion_duration : 60 # in minutes
  default_event_duration: [60, m]

defaults:
  title : 'My Example Database'
  fonts:   # if font names contain spaces, replace with underscore _
    Muli: ['300i', '400', '900']
    Neucha: ['400']
  js:
    index : ['js.popper', 'jquery', "js.jqueryUI", "js.tether", "js.bs", "js.moment", "js.moment_sv", 'js.cookie_api', 'js.fa', 'js.settings', 'js.buttons' , "js.natskol", "js.edit", "js.update", "js.slider", "js.cookie", "js.response", "js.tooltip", 'js.batch']
  css:
    index : ["css.bs", "css.jqueryUI",  "css.natskol"]
  placeholder:
    animals : [Albatross,Alpacka,Anakonda,Antilop,Apa,Björn,Bläckfisk,Blåmes,Blåval,Bofink,Buffel,Bältdjur,Bäver,Capybara,Delfin,Dromedar,Duva,Ekorre,Elefant,Fjäril,Fladdermus,Flamingo,Flodhäst,Får,Get,Giraff,Gorilla,Gris,Groda,Grävling,Gädda,Hamster,Hare,Hermelin,Hjort,Hund,Häst,Hök,Höna,Igelkott,Isbjörn,Järv,Kalkon,Kamel,Kanin,Katt,Ko,Koala,Kobra,Krabba,Krokodil,Känguru,Lama,Lejon,Leopard,Lodjur,Lämmel,Mammut,Marsvin,Mink,Mullvad,Murmeldjur,Myra,Mård,Noshörning,Näbbdjur,Näbbmus,Oxe,Padda,Papegoja,Piggsvin,Pingvin,Python,Påfågel,Ren,Räv,Rådjur,Råtta,Rödhake,Salamander,Schimpans,Sebra,Sengångare,Skata,Skunk,Sköldpadda,Snok,Sparv,Spindel,Späckhuggare,Struts,Svan,Säl,Talgoxe,Tapir,Tiger,Torsk,Tumlare,Tvättbjörn,Uggla,Undulat,Utter,Varg,Vessla,Vildsvin,Älg,Öring,Örn]
