translations:
  # should all be lowercase!
  colleague : 'Medarbetare'
  comment : 'Kommentar'
  confirmed : 'Bekräftad'
  coordinates : 'Koordinater'
  date : 'Datum'
  expirationdate : ''
  firstname : 'Förnamn'
  food : 'Specialkost'
  grade : 'Årskurs'
  group : 'Grupp'
  groupsak2 : 'Antal klasser åk 2'
  groupsak5 : 'Antal klasser åk 5'
  groupsfbk16 : 'Antal klasser FBK F-6'
  groupsfbk79 : 'Antal klasser FBK 7-9'
  hash : ''
  info : 'Information om gruppen'
  isactive : ''
  lastchange : 'Senast ändrat'
  lastname : 'Efternamn'
  location : 'Plats'
  longname : 'Utförligt namn'
  mail : 'Mejl'
  mailchimp : ''
  mobil : ''
  name : 'Namn'
  notes : 'Anteckningar om gruppen'
  numberstudents : 'Antal elever'
  parent : ''
  password : 'Lösenord'
  school : 'Skola'
  shortName : 'Kort Namn'
  status : ''
  topic : 'Tema'
  url : 'Länk'
  user : 'Ansvarig'
  value : 'Värde'
  visitorder : 'Besöksordning'